name: Update Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: zip -r master.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: master.zip

permissions:
  contents: write
